### ISSUE TITLE
Issue with attribute iterator

### ISSUE THREAD

**Issue by tafia** [hdhoang/luser#3]
> Pod titles in rust
> 
> Quick-xml doesn’t return the attributes iterator currently.

https://github.com/hdhoang/luser/blob/fc20bb7483e8bfee70544cd47f6bdc18b35765d2/src/main.rs#L252-L253

Can you explain what exactly is the error so I can fix it on quick-xml?

**Comment by hdhoang** [comment]
Hi, thank you for your concern. I have since updated to 0.1.6 and the issue is gone. I'll downgrade to 0.1.5 and reproduce here.

It was happening with XML responses from WA, such as http://api.wolframalpha.com/v2/query?input=mass%20of%20sun&appid=3JEW42-4XXE264A93
The first println! shows the start tag correctly, but the collected Vec was [Error(Malformed("Got 2 '=' tokens")]

Strangely, pasting that XML into a test case doesn't reproduce, so I haven't reported to you. I'll push my new version here.

**Comment by tafia** [comment]
ok thanks!
Don't hesitate if you see something weird
